// Verify fixtures (or a saved network JSON) against Wikidata. Usage: node scripts/verify-web.mjs [fixture...]
// Writes docs/verification.md and exits 1 when any line fails.
import fs from 'node:fs';
import { verifyNetwork, reportMarkdown } from '@metrocad/core';
// Known Wikidata network items for the bundled fixtures (skips the search step).
const QIDS = { paris: 'Q50716', london: 'Q20075', philadelphia: 'Q7451006', pittsburgh: 'Q7199143' };
const names = process.argv.slice(2).length ? process.argv.slice(2) : fs.readdirSync('packages/core/fixtures').filter((f) => f.endsWith('.json')).map((f) => f.replace('.json', ''));
const sections = ['# Verification against Wikidata', '', 'Each bundled network is checked against Wikidata: lines of the same transport network, their station counts (stations with a "connecting line" claim, closed stations excluded), termini and colours. Links go to the official route diagrams on Wikimedia Commons where Wikidata lists one. Regenerated by the `verify` workflow.', ''];
let failed = 0;
for (const n of names) {
  const file = n.endsWith('.json') ? n : `packages/core/fixtures/${n}.json`;
  const net = JSON.parse(fs.readFileSync(file, 'utf8'));
  process.stderr.write(`verifying ${n}…\n`);
  try {
    const rep = await verifyNetwork(net, { networkQid: QIDS[n] });
    await new Promise((r) => setTimeout(r, 6000));
    sections.push(reportMarkdown(rep), '');
    failed += rep.failed;
    console.log(`${n}: ${rep.passed} pass, ${rep.warned} warn, ${rep.failed} fail, ${rep.unmatched} unmatched`);
  } catch (e) { sections.push(`### ${n}\n\nverification error: ${e.message}\n`); console.log(`${n}: error ${e.message}`); }
}
fs.mkdirSync('docs', { recursive: true });
fs.writeFileSync('docs/verification.md', sections.join('\n'));
process.exit(failed ? 1 : 0);
